[package]
name = "example-runner"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
polkavm-derive = { version = "0.24.0" }
polkavm = { version = "0.24.0", features = ["std"] }
env_logger = { version = "0.11.6", default-features = false }